### ISSUE TITLE
The bot does not respond to any commands...

### ISSUE THREAD

**Issue by alecrespi78** [S0NN1/lex-arcana-telegram-bot#1]
Good morning,
the commands I send to the bot have no results.
Is the bot still working?

**Comment by S0NN1** [comment]
Hi @alecrespi78, glad someone is still interested in this project.
It was deployed on a RaspberryPi and I can deploy it again if you want to try it.
It is nowhere near production-ready but since it is open source you can deploy it yourself if you want (be sure to mention my profile if you do that)...
For anything else you can also contact me on Telegram @Sonni.
